
stages:
  - build
  - test

build:
  stage: build
  tags: [ios]
  allow_failure: false
  only:
    - devel
  script:
    - make

test:
  stage: test
  allow_failure: false
  only:
    - devel
  script:
    - make run

