stages:
  - build
  - deploy

build:
  stage: build
  tags: [ios]
  allow_failure: false
  only:
    - merge_requests
  script:
    - make
    - make run-test

deploy_patch:
  stage: deploy
  tags: [ios]
  allow_failure: false
  only:
    - devel
  rules:
    - if: '$GITLAB_USER_EMAIL != "dev.ios@cleevio.com"'
  script:
    - make all
    - ./deploy.sh patch

deploy_minor:
  stage: deploy
  tags: [ios]
  allow_failure: false
  only:
    - staging
  rules:
    - if: '$GITLAB_USER_EMAIL != "dev.ios@cleevio.com"'
  script:
    - make all
    - ./deploy.sh minor

deploy_major:
  stage: deploy
  tags: [ios]
  allow_failure: false
  only:
    - main
  rules:
    - if: '$GITLAB_USER_EMAIL != "dev.ios@cleevio.com"'
  script:
    - make all
    - ./deploy.sh major

